// // / 4- translate function

// english_array = [
//   "apple",
//   "banana",
//   "car",
//   "dog",
//   "elephant",
//   "flower",
//   "guitar",
//   "house",
//   "internet",
//   "jacket",
//   "kangaroo",
//   "lamp",
//   "mouse",
//   "notebook",
//   "orange",
//   "pencil",
//   "queen",
//   "rabbit",
//   "sun",
//   "table",
//   "umbrella",
//   "violin",
//   "window",
//   "xylophone",
//   "yacht",
//   "zebra",
//   "airplane",
//   "book",
//   "cat",
//   "dog",
//   "elephant",
//   "fish",
//   "guitar",
//   "hat",
//   "ice cream",
//   "jellyfish",
//   "kite",
//   "lemon",
//   "monkey",
//   "nest",
//   "orange",
//   "piano",
//   "queen",
//   "rose",
//   "strawberry",
//   "truck",
//   "unicorn",
//   "vase",
//   "watermelon",
//   "xylophone",
//   "yogurt",
//   "zebra",
//   "ant",
//   "ball",
//   "carrot",
//   "dog",
//   "elephant",
//   "flower",
//   "grape",
//   "house",
//   "ice cream",
//   "jacket",
//   "kiwi",
//   "lemon",
//   "mango",
//   "nest",
//   "orange",
//   "pear",
//   "quail",
//   "rabbit",
//   "strawberry",
//   "tomato",
//   "umbrella",
//   "violin",
//   "watermelon",
//   "xylophone",
//   "yogurt",
//   "zebra",
//   "apple",
//   "banana",
//   "car",
//   "dog",
//   "elephant",
//   "flower",
//   "guitar",
//   "house",
//   "internet",
//   "jacket",
//   "kangaroo",
//   "lamp",
//   "mouse",
//   "notebook",
//   "orange",
//   "pencil",
//   "queen",
//   "rabbit",
//   "sun",
//   "table",
//   "umbrella",
//   "violin",
//   "window",
//   "xylophone",
//   "yacht",
//   "zebra",
// ];
// uzbek_array = [
//   "olma",
//   "banan",
//   "mashina",
//   "it",
//   "fil",
//   "gul",
//   "gitara",
//   "uy",
//   "internet",
//   "kurtka",
//   "djeiran",
//   "lampa",
//   "sichqoncha",
//   "qog'oz",
//   "apelsin",
//   "qalam",
//   "malika",
//   "tovus",
//   "quyosh",
//   "stol",
//   "chomak",
//   "skripka",
//   "deraza",
//   "ksilofon",
//   "yaxta",
//   "zebra",
//   "samolyot",
//   "kitob",
//   "mushuk",
//   "it",
//   "fil",
//   "baliq",
//   "gitara",
//   "shlyapa",
//   "muzqaymoq",
//   "qurtoq",
//   "limon",
//   "mavna",
//   "maymun",
//   "tayorak",
//   "apelsin",
//   "piyano",
//   "malika",
//   "gul",
//   "qovun",
//   "yuk",
//   "begona",
//   "vaza",
//   "tarvuz",
//   "ksilofon",
//   "yog'urt",
//   "zebra",
//   "chiroq",
//   "to'p",
//   "sabzi",
//   "it",
//   "fil",
//   "gul",
//   "uzum",
//   "uy",
//   "muzqaymoq",
//   "kurtka",
//   "kiwi",
//   "limon",
//   "mango",
//   "tayorak",
//   "apelsin",
//   "nok",
//   "qush",
//   "tovus",
//   "pomidor",
//   "chomak",
//   "skripka",
//   "tarvuz",
//   "ksilofon",
//   "yog'urt",
//   "zebra",
//   "olma",
//   "banan",
//   "mashina",
//   "it",
//   "fil",
//   "gul",
//   "gitara",
//   "uy",
//   "internet",
//   "kurtka",
//   "djeiran",
//   "lampa",
//   "sichqoncha",
//   "qog'oz",
//   "apelsin",
//   "qalam",
//   "malika",
//   "tovus",
//   "quyosh",
//   "stol",
//   "chomak",
//   "skripka",
//   "deraza",
//   "ksilofon",
//   "yaxta",
//   "zebra",
// ];
// russian_array = [
//   "яблоко",
//   "банан",
//   "машина",
//   "собака",
//   "слон",
//   "цветок",
//   "гитара",
//   "дом",
//   "интернет",
//   "куртка",
//   "кенгуру",
//   "лампа",
//   "мышь",
//   "тетрадь",
//   "апельсин",
//   "карандаш",
//   "королева",
//   "кролик",
//   "солнце",
//   "стол",
//   "зонтик",
//   "скрипка",
//   "окно",
//   "ксилофон",
//   "яхта",
//   "зебра",
//   "самолет",
//   "книга",
//   "кот",
//   "собака",
//   "слон",
//   "рыба",
//   "гитара",
//   "шапка",
//   "мороженое",
//   "медуза",
//   "воздушный змей",
//   "лимон",
//   "обезьяна",
//   "гнездо",
//   "апельсин",
//   "пианино",
//   "королева",
//   "роза",
//   "клубника",
//   "грузовик",
//   "единорог",
//   "ваза",
//   "арбуз",
//   "ксилофон",
//   "йогурт",
//   "зебра",
//   "муравей",
//   "мяч",
//   "морковь",
//   "собака",
//   "слон",
//   "цветок",
//   "виноград",
//   "дом",
//   "мороженое",
//   "куртка",
//   "киви",
//   "лимон",
//   "манго",
//   "гнездо",
//   "апельсин",
//   "груша",
//   "куропатка",
//   "кролик",
//   "клубника",
//   "томат",
//   "зонтик",
//   "скрипка",
//   "арбуз",
//   "ксилофон",
//   "йогурт",
//   "зебра",
//   "яблоко",
//   "банан",
//   "машина",
//   "собака",
//   "слон",
//   "цветок",
//   "гитара",
//   "дом",
//   "интернет",
//   "куртка",
//   "кенгуру",
//   "лампа",
//   "мышь",
//   "тетрадь",
//   "апельсин",
//   "карандаш",
//   "королева",
//   "кролик",
//   "солнце",
//   "стол",
//   "зонтик",
//   "скрипка",
//   "окно",
//   "ксилофон",
//   "яхта",
//   "зебра",
// ];
// function translateF(word, lang) {
//   if (!english_array.includes(word)) {
//     console.log("Bunday so'z yo'q");
//     return;
//   }
//   let index = english_array.indexOf(word);
//   if (lang === "uz") {
//     if (english_array.includes(word)) {
//       console.log(uzbek_array[index]);
//     }
//   } else if (lang === "ru") {
//     if (english_array.includes(word)) {
//       console.log(russian_array[index]);
//     }
//   }
// }

// translateF("car", "uz");

// 2-usul

let dictionary = {
  apple: {
    uz: "Olma",
    ru: "Yabloka",
  },
  banana: {
    uz: "Banan",
    ru: "Banan ru",
  },
};

function t(soz, til) {
  let word = dictionary[soz.toLowerCase().trim()];
  if (!word) {
    return soz;
  }
  let translatedWord = word[til];
  if (!translatedWord) {
    return soz;
  }
  return translatedWord;
}
let userWord = prompt("So'z kiriting").toLocaleLowerCase().trim();
let userLang = prompt("Tilni kiriting").toLocaleLowerCase().trim();
console.log(t(userWord, userLang));
